// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxKb4x7MBCPrwk-n-hLhm9PKc9RWhABwA',
    appId: '1:453829112125:web:3fdf7875805301bee6d554',
    messagingSenderId: '453829112125',
    projectId: 'salespro-19e86',
    authDomain: 'salespro-19e86.firebaseapp.com',
    storageBucket: 'salespro-19e86.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
      apiKey: 'AIzaSyBSFHZWx7Fm_O5RJlGZJGRUMl9ro2ZGLMg',
      appId: '1:264423022274:android:49501726bb97e7929c255b',
      messagingSenderId: '264423022274',
      projectId: 'piik-seller',
      storageBucket: 'piik-seller.appspot.com',
      databaseURL: 'https://piik-seller-default-rtdb.asia-southeast1.firebasedatabase.app/');

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpb8iSLDO_I_5pvVn9Qy57bR2GW_7shVs',
    appId: '1:453829112125:ios:a65a63d927a1f664e6d554',
    messagingSenderId: '264423022274',
    projectId: 'piik-seller',
    storageBucket: 'piik-seller.appspot.com',
    iosClientId: '264423022274-kkfkl2skvd1p7v8tol780ja9dlmmuul9.apps.googleusercontent.com',
    iosBundleId: 'com.piik.pos',
    databaseURL: 'https://piik-seller-default-rtdb.asia-southeast1.firebasedatabase.app/'
  );
}
